# Generated by Django 3.2.25 on 2026-07-18 09:39

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('shift', models.CharField(choices=[('Day Shift', 'Day Shift'), ('Night Shift', 'Night Shift'), ('All_Shift', 'All Shift')], db_index=True,
                                           max_length=15)),
                ('delivery_shift',
                 models.CharField(blank=True, choices=[('Day Shift', 'Day Shift'), ('Night Shift', 'Night Shift'), ('All_Shift', 'All Shift')],
                                  help_text="Shift saat laporan ini 'dikirim' atau saat transaksi yang memicu pembuatan laporan dicatat.", max_length=15,
                                  null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('notif_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('today_rom', models.FloatField(default=0.0)),
                ('today_jetty', models.FloatField(default=0.0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='report_pdf/')),
                ('encoded_key', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Report Summary',
                'verbose_name_plural': 'Daily Report Summaries',
                'ordering': ['-report_date', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='MasterManpower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(blank=True, db_column='no', max_length=255, null=True)),
                ('nrp', models.CharField(blank=True, db_column='nrp', max_length=255, null=True, unique=True)),
                ('nama', models.CharField(blank=True, db_column='nama', max_length=255, null=True)),
                ('departement', models.CharField(blank=True, db_column='departement', max_length=255, null=True)),
                ('jabatan', models.CharField(blank=True, db_column='jabatan', max_length=255, null=True)),
                ('jabatan_2', models.CharField(blank=True, db_column='jabatan_2', max_length=255, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, db_column='jenis_kelamin', max_length=255, null=True)),
                ('poh', models.CharField(blank=True, db_column='poh', max_length=255, null=True)),
                ('kompetensi', models.CharField(blank=True, db_column='kompetensi', max_length=255, null=True)),
                ('tgl_lahir', models.DateTimeField(blank=True, db_column='tgl_lahir', null=True)),
                ('umur', models.FloatField(blank=True, db_column='umur', null=True)),
                ('pendidikan', models.CharField(blank=True, db_column='pendidikan', max_length=255, null=True)),
                ('mulai_bekerja', models.DateTimeField(blank=True, db_column='mulai_bekerja', null=True)),
                ('doh_as_opt', models.DateTimeField(blank=True, db_column='doh_as_opt', null=True)),
                ('status_karyawan', models.CharField(blank=True, db_column='status_karyawan', max_length=255, null=True)),
                ('ket', models.CharField(blank=True, db_column='ket', max_length=255, null=True)),
                ('keterangan', models.CharField(blank=True, db_column='keterangan', max_length=255, null=True)),
                ('tgl_turnover', models.DateTimeField(blank=True, db_column='tgl_turnover', null=True)),
                ('levels', models.CharField(blank=True, db_column='levels', max_length=255, null=True)),
                ('opt_cn', models.CharField(blank=True, db_column='opt_cn', max_length=255, null=True)),
                ('opt_group', models.CharField(blank=True, db_column='opt_group', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=255, null=True)),
                ('pas_foto', models.ImageField(blank=True, null=True, upload_to='pas_foto/')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('kontrak_terakhir', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_profile',
                                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('parent_comment',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reports.reportcomment')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                             to='reports.dailyreportsummary')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to='reports.mastermanpower', to_field='nrp')),
            ],
        ),
        migrations.CreateModel(
            name='ReportReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('reacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='reports.reportcomment')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions',
                                             to='reports.dailyreportsummary')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_given', to='reports.mastermanpower', to_field='nrp')),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
            },
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_nik',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_devices', to='reports.mastermanpower',
                                   to_field='nrp')),
            ],
            options={
                'verbose_name': 'FCM Device',
                'verbose_name_plural': 'FCM Devices',
            },
        ),
        migrations.AddField(
            model_name='dailyreportsummary',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports_authored',
                                    to='reports.mastermanpower', to_field='nrp'),
        ),
        migrations.AddConstraint(
            model_name='reportreaction',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('comment__isnull', True), ('report__isnull', False)), models.Q(('comment__isnull', False), ('report__isnull', True)),
                               _connector='OR'), name='either_report_or_comment_not_null'),
        ),
        migrations.AddConstraint(
            model_name='reportreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', True)), fields=('report', 'user'), name='unique_report_reaction'),
        ),
        migrations.AddConstraint(
            model_name='reportreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('report__isnull', True)), fields=('comment', 'user'), name='unique_comment_reaction'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreportsummary',
            unique_together={('report_date', 'shift')},
        ),
    ]
