# Generated by Django 3.2.25 on 2026-07-23 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0003_dailyreportsummary_timestamps_db_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastermanpower',
            options={'verbose_name': 'Master Manpower', 'verbose_name_plural': 'Master Manpower'},
        ),
        migrations.AlterModelOptions(
            name='reportcomment',
            options={'verbose_name': 'Report Comment', 'verbose_name_plural': 'Report Comments'},
        ),
    ]
