# Generated by Django 3.2.25 on 2026-09-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_sync_model_meta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Semantic version, e.g. 2.1.0', max_length=20)),
                ('build_number', models.PositiveIntegerField(help_text="Monotonic build number, matches pubspec '+N'")),
                ('apk_file', models.FileField(upload_to='apk/')),
                ('changelog', models.TextField(blank=True, default='')),
                ('mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Newest active release is the one served to clients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'App Release',
                'verbose_name_plural': 'App Releases',
                'ordering': ['-build_number'],
            },
        ),
    ]
